version: 2

models:
  - name: customer_orders
    description: This table has the dates for the first and most recent orders. It also has the number of orders for each customer

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_order
        description:  Date of the first order of the customer

      - name: most_recent_order
        description: Date of the most recent order of the customer

      - name: number_of_orders
        description: Number of orders for the customer
  
  - name: customer_payments
    description: This table has the total payments done by a customer

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
      
      - name: total_amount
        description: Total amount paid by the customer