version: 2
models:
  - name: stg_customers
    columns:
      - name: customer_id
        data_type: integer
        description: Unique identifier for a customer
        tests:
          - not_null
          - unique
      - name: first_name
        data_type: varchar
      - name: last_name
        data_type: varchar
    description: Importing customer demographic data from source
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values:
                - credit_card
                - coupon
                - bank_transfer
                - gift_card
